

DELETE FROM tutoria;
DELETE FROM curso;
DELETE FROM orientacion;


INSERT INTO orientacion (nombre, email, centro, eliminado) VALUES
('Juan Pérez', 'juan.perez', NULL,false),
('María Gómez', 'maria.gomez', NULL,false),
('Carlos Ramírez', 'carlos.ramirez', NULL,false),
('Ana Torres', 'ana.torres', NULL,false),
('Pedro Martínez', 'pedro.martinez', NULL,false);


/*
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33002488','ALEJANDRO CASONA','CANGAS DEL NARCEA','acasona@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33019695','ALEJANDRO CASONA','GIJON','acasonag@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33006445','ALFONSO CAMIN','GIJON','alfonsoc@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33013000','ALFONSO II','OVIEDO','alfonso2@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33027989','ALTO NALON','LAVIANA','craaltonalon@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33020090','ALTO NALON','LAVIANA','altonalo@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33020910','ALVARO FLOREZ ESTRADA','SOMIEDO','polasomi@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33012627','AMOR DE DIOS','OVIEDO','amordedios@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33017078','AMOR MISERICORDIOSO','SIERO','amormisericordioso@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33028878','ANDOLINA','GIJON','andolina@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33006044','ANGEL DE LA GUARDA','GIJON','angeldelaguardagi@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33021768','ANGEL DE LA GUARDA','OVIEDO','angeldelaguardaov@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33022967','ANGEL MUÑIZ TOCA','OVIEDO','angelmuniztoca@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33010631','ANICETO SELA','MIERES DEL CAMINO','anicetos@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33020557','ANTONIO MACHADO','GIJON','antoniom@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33001460','APOLINAR GARCIA HEVIA','AVILES','apolinar@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33013012','ARAMO','OVIEDO','aramo@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33015914','ARZOBISPO VALDES-SALAS','SALAS','arzobisp@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33004941','ASTURAMERICA','CUDILLERO','asturame@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33017248','ASTURES','SIERO','astures@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33005404','ASTURIAS','GIJON','asturias@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33024113','ASTURIAS EDUCACION','AVILES','fpaeducacion@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33020570','ATALIA','GIJON','atalia@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33028660','ATALIA','GIJON','eeiatalia@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33027412','AURELIO MENENDEZ','IBIAS','aureliom@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33012639','AUSEVA','OVIEDO','auseva@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33023194','AVELINA CERRA','RIBADESELLA','avelinac@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33020983','AVILES','AVILES','ceaavile@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33028684','AVILES','AVILES','cifpaviles@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33022724','AVILES','AVILES','eoiavile@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33700015','AVILES-OCCIDENTE','AVILES','cpravile@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33028295','AYALGAS','ALLER','ayalgas@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33023443','BAJO NALON','PRAVIA','bajonalo@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33013152','BAUDILIO ARCE','OVIEDO','baudilio@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33029147','BEATA IMELDA-SANTO TOMÁS','LANGREO','imeldatomas@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33005337','BEGOÑA','GIJON','begona@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33029287','BELLO','ALLER','altoalle@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33001538','BELMONTE','BELMONTE DE MIRANDA','belmonte@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33008031','BENEDICTO BEMBIBRE TORRE','LANGREO','lada@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33007929','BENJAMIN MATEO','LANGREO','benjamin@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33000017','BERDUCEDO','ALLANDE','berduced@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33010722','BERNALDO DE QUIROS','MIERES DEL CAMINO','bernaldo@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33006883','BERNARDO GURDIEL','GRADO','bernardo@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33027709','BERNARDO SOPEÑA','LLANERA','camparina@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33028647','BIMENES','BIMENES','eeibimenes@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33004631','BRAULIO VIGON','COLUNGA','brauliov@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33012378','BUENAVISTA I','OVIEDO','buenavis@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33022581','BUENAVISTA II','OVIEDO','buenavi2@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33027357','CABAÑAQUINTA','ALLER','cabanaqu@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33023339','CABO PEÑAS','GOZON','cabopena@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33023224','CABRUÑANA','AVILES','fpcabrunana@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33029263','CABRUÑANA','AVILES','fpcabrunana@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33005210','CABUEÑES','GIJON','cabuenes@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33006135','CALDERON DE LA BARCA','GIJON','calderon@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33029238','CAMPUS FP GIJON SOCIAL MEDIA','GIJON','campusfpgijon@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33003651','CANDAS','CARREÑO','candas@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33028702','CANGAS DE ONIS','CANGAS DE ONIS','eeiconis@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33002521','CANGAS DEL NARCEA','CANGAS DEL NARCEA','ehcangas@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33028325','CANGAS DEL NARCEA','CANGAS DEL NARCEA','eoicangas@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33027497','CANGAS DEL NARCEA','CANGAS DEL NARCEA','iescangas@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33017388','CARBAYIN BAJO','SIERO','carbayin@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33027369','CARLOS BOUSOÑO','BOAL','boal@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33028672','CARMEN RUIZ TILVE','OVIEDO','corredoria3@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33024071','CARMEN Y SEVERO OCHOA','VALDES','carmenys@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33027722','CARMÍN','SIERO','carmin@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33001393','CARREÑO MIRANDA','AVILES','carrenom@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33021902','CASTIELLO DE BERNUECES','GIJON','bernuece@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33022943','CASTILLO DE GAUZON','CASTRILLON','castillo@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33023340','CASTRILLON - ILLAS','CASTRILLON','castrill@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33021008','CAUDAL','MIERES DEL CAMINO','ceamiere@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33017297','CELESTINO MONTOTO SUAREZ','SIERO','celestin@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33029226','CENAFE ESCUELAS','OVIEDO','cenafe@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33024186','CENTRO DE DANZA KAREL','GIJON','karel@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33029007','CENTRO DE EDUCACION INFANTIL OVIDA','OVIEDO','eeiovida@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33027758','CENTRO DE ESTUDIOS MÚLTIPLES DENTALES','OVIEDO','cemd@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33029196','CENTRO DE FORMACIÓN ACADÉMICA DE ENTRENADORES DE FÚTBOL','GIJON','acadef.asturias@gmail.com');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33027618','CENTRO IMAGEN,SONIDO E INFORMATICA','NOREÑA','cisei@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33027503','CENTRO-ORIENTE','SIERO','cepasiero@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33028052','CEP EUROPEO FORMACION','AVILES','cefvm@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33028490','CERDEÑO','OVIEDO','fpcerdeno@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33027382','CERREDO','DEGAÑA','jmsuarez@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33006925','CESAR RODRIGUEZ','GRADO','cesarrod@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33015902','CHAMBERI','SALAS','chamberi@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33028477','CIENCIAS RADIOLÓGICAS','GIJON','fpcradio@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33022852','CLARA CAMPOAMOR','LANGREO','claracam@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33021938','CLARIN','GIJON','claringi@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33012184','COLLOTO','OVIEDO','roces@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33028428','COLLOTO','OVIEDO','eeicolloto@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33027552','COLOMBRES','RIBADEDEVA','ribadede@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33028465','COLORES','GIJON','colores@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33028210','COMUNICACIÓN, IMAGEN Y SONIDO','LANGREO','imagenysonido@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33006172','COMUNIDAD NATAHOYO-ESCUELA REVILLAGIGEDO','GIJON','fundacionrevillagigedo@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33024095','CONCEJO DE TINEO','TINEO','concejot@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33011842','CONDADO DE NOREÑA','NOREÑA','condado@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33022669','CONSERVATORIO ELEMENTAL DE MÚSICA','MIERES DEL CAMINO','conmiere@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33023777','CONSERVATORIO MUNICIPAL PROFESIONAL DE MUSICA OCCIDENTE "COAS"','VALDES','conluarc@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33022220','CONSERVATORIO MUNICIPAL PROFESIONAL DE MUSICA VALLE DEL NALÓN','LANGREO','connalon@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33021801','CONSERVATORIO PROFESIONAL DE MUSICA','AVILES','conavile@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33027564','CONSERVATORIO PROFESIONAL DE MÚSICA ANSELMO GONZÁLEZ DEL VALLE','OVIEDO','cpm@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33022271','CONSERVATORIO PROFESIONAL DE MUSICA Y DANZA DE GIJON','GIJON','congijon@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33027576','CONSERVATORIO SUPERIOR DE MUSICA EDUARDO M. TORNER','OVIEDO','conovied@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33005881','CORAZON DE MARIA','GIJON','corazondemaria@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33015689','CORNELLANA','SALAS','cornella@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33023972','CORVERA DE ASTURIAS','CORVERA DE ASTURIAS','corvera@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33016839','COTAYO','SIERO','elcotayo@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33006721','CRISTO DEL SOCORRO','GOZON','cristode@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33007978','CUENCA DEL NALON','LANGREO','cuencade@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33700040','CUENCAS MINERAS','LANGREO','cprnc@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33004539','DARIO FREAN BARREIRA','COAÑA','dariofre@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33008387','DAVID VAZQUEZ MARTINEZ','LAVIANA','davidvaz@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33029135','DEL DEPORTE','AVILES','cifpdeldeporte@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33029044','DEL MAR','GIJON','maritimo@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33013048','DOCTOR FLEMING','OVIEDO','fleming@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33012411','DOLORES MEDIO','OVIEDO','doloresm@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33028246','DOLORES MEDIO','OVIEDO','eeidoloresmedio@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33006101','DOÑA JIMENA','GIJON','jimena@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33012640','DULCE NOMBRE DE JESUS','OVIEDO','dulcenombredejesus@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33022190','ECOLE','LLANERA','colecole@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33022062','EDES','TAPIA DE CASARIEGO','edes@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33022104','EDUARDO MARTINEZ TORNER','GIJON','eduardom@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33023996','EL BATAN','MIERES DEL CAMINO','batan@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33024290','EL BIBIO','GIJON','ceibibio@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33016177','EL BOSQUIN','SAN MARTIN DEL REY AURELIO','elbosqui@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33028222','EL CARBAYO','CASTRILLON','eeielcarbayo@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33021513','EL CARBAYU','SIERO','elcarbay@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33028349','EL CASCAYU','LAVIANA','elcascayu@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33016116','EL COTO','SAN MARTIN DEL REY AURELIO','elcoto@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33028571','EL FRANCO','EL FRANCO','eeielfranco@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33022268','EL FUEJO','CANGAS DEL NARCEA','elfuejo@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33021653','EL LLANO','GIJON','elllano@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33028261','EL NIAL','LENA','eeipoladelena@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33028283','EL NIERU','COLUNGA','eeicolunga@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33016025','EL PARQUE','SAN MARTIN DEL REY AURELIO','elparque@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33021549','EL PASCON','TINEO','elpascon@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33022131','EL PILES','GIJON','elpiles@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33028143','EL PIYAVAN','VEGADEO','vegadeo@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33014302','EL PLAGANON','PILOÑA','plaganon@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33014120','EL PRIAL','PILOÑA','elprial@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33022098','EL QUIRINAL','AVILES','elquirin@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33028696','EL QUIRINAL','AVILES','eeiquirinal@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33027400','EL SALVADOR','GRANDAS DE SALIME','elsalvad@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33029275','EL SUEVE','PARRES','sarriond@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33028799','EL TEXU','CASTRILLON','eeieltexu@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33003845','EL TRUÉBANU','CASO','eltruebanu@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33028659','EL TURULLON','CASTROPOL','eeiturullon@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33021859','EL VALLIN','CASTRILLON','elvallin@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33013346','EL VILLAR','OVIEDO','elvillar@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33008351','ELENA SANCHEZ TAMARGO','LAVIANA','elenasan@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33023534','ELISA Y LUIS VILLAMIL','VEGADEO','elisaylu@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33022359','EMILIO ALARCOS','GIJON','emilioal@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33001435','ENRIQUE ALONSO','AVILES','enriquea@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33021896','ENRIQUE TRUAN','GIJON','enriquetruan@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33700520','EQUIPO DE ORIENTACION EDUCATIVA DE AVILÉS','AVILES','eoaviles@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33700532','EQUIPO DE ORIENTACION EDUCATIVA DE GIJON','GIJON','eogijon@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33700556','EQUIPO DE ORIENTACION EDUCATIVA DE GRADO','GRADO','eogrado@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33700593','EQUIPO DE ORIENTACION EDUCATIVA DE NOROCCIDENTE','VEGADEO','eovegade@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33700601','EQUIPO DE ORIENTACION EDUCATIVA DE ORIENTE','LLANES','eollanes@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33700519','EQUIPO DE ORIENTACION EDUCATIVA DE OVIEDO','OVIEDO','eooviedo@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33700568','EQUIPO DE ORIENTACIÓN EDUCATIVA DE SIERO-INFIESTO','SIERO','eosiero@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33700581','EQUIPO DE ORIENTACION EDUCATIVA DE SUROCCIDENTE','CANGAS DEL NARCEA','eocangas@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33700571','EQUIPO DE ORIENTACIÓN EDUCATIVA DEL CAUDAL','MIERES DEL CAMINO','eocaudal@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33700544','EQUIPO DE ORIENTACION EDUCATIVA DEL NALON','LANGREO','eonalon@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33700507','EQUIPO REGIONAL PARA LA ATENCIÓN DEL ALUMNADO CON NECESIDAD ESPECIFICA','OVIEDO','eqregional@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33027795','ESCOLINOS','GIJON','escolinos@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33028398','ESCUELA ASTURIANA DE ENTRENADORES DE FÚTBOL','GIJON','easef@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33013115','ESCUELA DE ARTE','OVIEDO','earte@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33029202','ESCUELA DE ESTUDIOS AVANZADOS DE FUTBOL','GIJON','eeavanzados@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33024149','ESCUELA DE HOSTELERIA Y TURISMO DE GIJON','GIJON','hosteler@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33029172','ESCUELA DE MONTAÑA CANGAS DE ONIS-PICOS DE EUROPA','CANGAS DE ONIS','empicosdeeuropa@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33028635','ESCUELA DE TURISMO DE ASTURIAS','OVIEDO','fpturismo@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33024265','ESCUELA EUROPEA','OVIEDO','fpesceur@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33023030','ESCUELA OFICIAL DE IDIOMAS','LANGREO','eoilangr@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33027515','ESCUELA SUPERIOR DE ARTE DEL PRINCIPADO','AVILES','esapa@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33027621','ESCUELA SUPERIOR DE ARTE DRAMÁTICO DEL PRINCIPADO DE ASTURIAS','GIJON','esad@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33029019','ESCUELAS CENETED','OVIEDO','eceneted@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33020272','ESCULTOR JUAN DE VILLANUEVA','SIERO','escultor@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33029071','EUGENIA ASTUR-LA ESPINA','SALAS','laespina@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33007917','EULALIA ALVAREZ LORENZO','LANGREO','eulaliaa@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33020314','EVARISTO VALLE','GIJON','evaristo@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33020545','FEDERICO GARCIA LORCA','GIJON','federico@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33000649','FELECHOSA','ALLER','felechos@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33006160','FERNANDEZ VALLIN','GIJON','fvallin@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33029123','FORMACION DEPORTIVA DE LLANES','LLANES','fdeportivallanes@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33029159','FORMACION DEPORTIVA INTERNACIONAL','GIJON','fdinternacional@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33029101','FORMACION SANITARIA PRINCIPADO SL','OVIEDO','fsanitaria@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33012433','FOZANELDI','OVIEDO','fozaneld@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33004771','FRANCISCO FDEZ. GLEZ.','CORVERA DE ASTURIAS','francisc@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33012767','FUNDACION MASAVEU','OVIEDO','fundacionmasaveu@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33012615','FUNDACION PADRE VINJOY','OVIEDO','padrevinjoy@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33023170','GALILEO GALILEI','NAVIA','galileo@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33028829','GARABATOS','LANGREO','eeigarabatos@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33028982','GASPAR MELCHOR JOVELLANOS','GIJON','jovellan@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33027953','GERA-CUARTO DE LOS VALLES','TINEO','gera@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33013097','GERMAN FERNANDEZ RAMOS','OVIEDO','germanfe@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33029160','GERONTOLOGICO JOVELLANOS CENTRO DE FORMACION','GIJON','info@formacionjovellanos.com');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33008156','GERVASIO RAMOS','LANGREO','gervasio@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33029214','GESTA I-II','OVIEDO','cpgesta@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33020995','GIJON','GIJON','ceagijon@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33022621','GIJON','GIJON','eoigijon@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33700027','GIJON-ORIENTE','GIJON','cprgijon@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33022116','GLORIA FUERTES','GIJON','gloriafuertes@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33017819','GLORIA RODRIGUEZ','SOTO DEL BARCO','gloriaro@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33028301','GRADO','GRADO','eeigrado@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33017091','GRANDA','SIERO','granda@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33027643','GREMIO DE ARTESANOS CONFITEROS PRINCIPADO AST.','OVIEDO','gaconfite@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33004874','GUDIN','CORVERA DE ASTURIAS','gudin@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33020491','GUIMARAN VALLE','CARREÑO','guimaran@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33020703','HERMANOS ARREGUI','SIERO','hermanos@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33006081','HONESTO BATALON','GIJON','honestob@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33011325','HORACIO FERNANDEZ INGUANZO','MORCIN','morcin@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33028866','ILLANO','ILLANO','illano@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33003948','INFANTA LEONOR','CASTRILLON','piedrasb@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33024061','INFIESTO','PILOÑA','infiesto@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33029241','INSTITUTO DE ESTUDIOS EN EMERGENCIAS Y CATASTROFES SL','OVIEDO','info@ieducae.es');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33021771','ISLA DE LA DEVA','CASTRILLON','isladeva@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33006652','JACINTO BENAVENTE','GIJON','jacintob@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33028192','JARDÍN DE INFANCIA CANTOS','AVILES','cantos@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33008181','JERONIMO GONZALEZ','LANGREO','jeronimo@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33005179','JESUS ALVAREZ VALDES','EL FRANCO','jesusalv@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33023686','JESUS NEIRA','LENA','jesusnei@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33008168','JOSE BERNARDO','LANGREO','josebern@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33009392','JOSE GARCIA FERNANDEZ','VALDES','josegarciafernandez@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33003936','JOSE LUIS GARCIA RODRIGUEZ','CASTRILLON','joseluis@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33006263','JOSE ZORRILLA','GIJON','zorrilla@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33018861','JOVELLANOS','VEGADEO','jovellav@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33013796','JOVELLANOS','PEÑAMELLERA BAJA','jovellap@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33016372','JUAN JOSE CALVO MIGUEL','SAN MARTIN DEL REY AURELIO','juanjose@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33021756','JUAN LUIS IGLESIAS PRADA','LANGREO','juanluis@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33013085','JUAN RODRIGUEZ MUÑIZ','OVIEDO','juanrodr@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33006068','JULIAN GOMEZ ELISBURU','GIJON','juliango@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33014442','JULIO RODRIGUEZ VILLANUEVA','PILOÑA','juliorod@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33014090','L'ABLANU','PILOÑA','cpinfies@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33028787','L'ENTREGU','SAN MARTIN DEL REY AURELIO','eeientregu@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33005878','LA ASUNCION','GIJON','laasuncion@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33006718','LA CANAL','GOZON','lacanal@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33001472','LA CARRIONA-MIRANDA','AVILES','lacarrio@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33006184','LA COROLLA','GIJON','collacorolla@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33023431','LA COROÑA','NAVA','lacorona@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33012044','LA CORREDORIA','OVIEDO','lacorred@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33028817','LA CORREDORIA','OVIEDO','eeicorredoria@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33028453','LA CORREDORIA','OVIEDO','iescorredoria@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33017212','LA ERIA','SIERO','laeria@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33021781','LA ERIA','OVIEDO','cplaeria@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33022700','LA ERIA','OVIEDO','ieseria@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33005428','LA ESCUELONA','GIJON','laescuelona@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33028581','LA ESTELA','COAÑA','eeilaestela@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33028881','LA FLORIDA','OVIEDO','eeilaflorida@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33024277','LA FRESNEDA','SIERO','fresneda@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33005891','LA INMACULADA','GIJON','lainmaculada@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33012691','LA INMACULADA','OVIEDO','lainmaculadao@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33008120','LA LLAMIELLA','LANGREO','lallamie@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33027667','LA MAGDALENA','AVILES','eeiaviles@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33020843','LA MAGDALENA','AVILES','lamagdal@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33028337','LA MANZANA','SIERO','lamanzana@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33023121','LA MARINA','VILLAVICIOSA','lamarina@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33027761','LA MARINERA','CARREÑO','eeicandas@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33006962','LA MATA','GRADO','lamata@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33005969','LA MILAGROSA','GIJON','lamilagrosa@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33012652','LA MILAGROSA','OVIEDO','virgenmilagrosa@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33027734','LA OLIVA','VILLAVICIOSA','laoliva@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33028003','LA PALOMA','CASTROPOL','castropo@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33028091','LA PIXUETINA','CUDILLERO','pixuetina@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33018113','LA PLAZA','TEVERGA','laplaza@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33029081','LA QUINTA'L TEXU','OVIEDO','ceilaquinta@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33023169','LA QUINTANA','LANGREO','laquinta@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33021021','LA SALLE','LANGREO','lasallel@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33027679','LA SERENA','GIJON','laserena@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33028350','LA TOBA','AVILES','eeiavilessur@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33022074','LA VALLINA','GOZON','lavallin@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33027370','LAS ARENAS','CABRALES','lasarena@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33022128','LAS MESTAS','GIJON','lasmestas@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33004795','LAS VEGAS','CORVERA DE ASTURIAS','lasvegas@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33010606','LAS VEGAS','MIERES DEL CAMINO','figaredo@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33028088','LAS VEGAS','CORVERA DE ASTURIAS','eeicorvera@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33010679','LASTRA','MIERES DEL CAMINO','lastra@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33012147','LATORES','OVIEDO','latores@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33021926','LAVIADA','GIJON','laviada@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33027965','LENA','LENA','huernap@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33013024','LEOPOLDO ALAS-CLARIN','OVIEDO','leopoldo@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33027801','LES XANES','MIERES DEL CAMINO','lesxanes@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33010643','LICEO MIERENSE','MIERES DEL CAMINO','liceomie@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33023984','LLANERA','LLANERA','llanera@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33028362','LLANES','LLANES','eeillanes@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33023510','LLANES','LLANES','eoillane@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33023522','LLANES','LLANES','llanes@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33010539','LLANES NUMERO DOS','LLANES','llanes2@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33010527','LLANES NUMERO UNO','LLANES','llanes1@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33022256','LLARANES','AVILES','llaranes@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33027606','LLERON-CLARIN','MIERES DEL CAMINO','clarin@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33022578','LLOREU','GIJON','lloreu@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33021070','LOGREZANA','CARREÑO','logrezan@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33005908','LOPEZ Y VICUÑA','GIJON','lopezyvicuna@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33022347','LORENZO NOVO MIER','OVIEDO','lorenzon@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33016918','LOS CAMPONES','SIERO','campones@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33004849','LOS CAMPOS','CORVERA DE ASTURIAS','loscampo@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33005398','LOS CAMPOS','GIJON','campos@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33028271','LOS GIGANTINOS','CANGAS DEL NARCEA','gigantinos@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33027874','LOS PERICONES','GIJON','lospericones@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33027783','LOS PLAYINOS','GIJON','losplayinos@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33028106','LOS RAITANES','GIJON','raitanes@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33009938','LOS ROBLES','LLANERA','losrobles@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33012755','LOYOLA','OVIEDO','loyola@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33027680','LUANCO','GOZON','eeiluanco@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33023509','LUARCA','VALDES','eoiluarc@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33004710','LUCES','COLUNGA','luces@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33009872','LUGO DE LLANERA','LLANERA','lugollan@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33027813','LUIS OCHOA DE ALBORNOZ','VALDES','luisochoa@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33001216','LUISA DE MARILLAC','AVILES','luisademarillac@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33011416','MAESTRA HUMBELINA ALONSO CARREÑO','MUROS DE NALON','maestrah@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33002476','MAESTRO CASANOVA','CANGAS DEL NARCEA','maestroc@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33027990','MAESTRO DON JOSE ANTONIO ROBLES','ALLER','maestrojrobles@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33012536','MAESTRO JAIME BORRAS','OVIEDO','guillenl@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33019397','MALIAYO','VILLAVICIOSA','maliayo@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33028209','MANTENIMIENTO Y LOS SERVICIOS A LA PRODUCCION','LANGREO','mantenimiento@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33004102','MANUEL ALVAREZ IGLESIAS','CASTRILLON','manuelal@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33015392','MANUEL FERNANDEZ JUNCOS','RIBADESELLA','manuelfe@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33019701','MANUEL MARTINEZ BLANCO','GIJON','manuelma@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33001034','MARCELO GAGO','AVILES','marcelog@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33001095','MARCOS DEL TORNIELLO','AVILES','marcosde@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33027710','MARÍA BALBÍN','OVIEDO','mbalbin@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33019749','MARIA INMACULADA','OVIEDO','mariainmaculadao@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33008363','MARIA INMACULADA','LAVIANA','mariainmaculada@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33017972','MARQUES DE CASARIEGO','TAPIA DE CASARIEGO','marques@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33020296','MARTIMPORRA','BIMENES','martimpo@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33021860','MATA JOVE','GIJON','matajove@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33004679','MATEMATICO PEDRAYES','COLUNGA','matemati@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33008405','MAXIMILIANO ARBOLEYA','LAVIANA','maximili@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33017339','MERES','SIERO','colmeres@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33023212','MIERES','MIERES DEL CAMINO','eoimiere@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33005350','MIGUEL DE CERVANTES','GIJON','miguelde@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33020569','MIGUEL HERNANDEZ','GIJON','miguelhe@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33029020','MONSACRO','MORCIN','eeimonsacro@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33022141','MONTE NARANCO','OVIEDO','naranco@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33005945','MONTEDEVA','GIJON','montedeva@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33028593','MONTENUÑO','OVIEDO','eeimontenuno@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33021914','MONTEVIL','GIJON','montevil@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33028568','MONTEVIL','GIJON','eeimontevil@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33022694','MONTEVIL','GIJON','iesmonte@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33005325','MONTIANA','GIJON','montiana@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33000467','MOREDA','ALLER','cpmoreda@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33022301','MUSICALIA','OVIEDO','musicalia@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33023893','NALON','SAN MARTIN DEL REY AURELIO','ceanalon@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33012354','NARCISO SANCHEZ','OVIEDO','narcisos@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33027461','NARSEO VALLINA','LANGREO','fpenarseovallina@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33028441','NAVA','NAVA','eeinava@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33012664','NAZARET','OVIEDO','nazaret@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33021872','NICANOR PIÑOLE','GIJON','nicanorp@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33006494','NOEGA','GIJON','noega@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33028431','NOREÑA','NOREÑA','eeinorena@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33023911','NOREÑA','NOREÑA','norena@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33028027','NOROCCIDENTE','VEGADEO','ceavegadeo@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33011878','NUESTRA SEÑORA DE COVADONGA','NOREÑA','ntrasradecovadongan@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33010451','NUESTRA SEÑORA DE FATIMA','LLANES','ntrasradefatima@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33005106','NUESTRA SEÑORA DE LA HUMILDAD','CUDILLERO','nuestras@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33001174','NUESTRA SEÑORA DEL BUEN CONSEJO','AVILES','sradelbuenconsejo@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33008171','NUESTRA SEÑORA DEL ROSARIO','LANGREO','ntrasradelrosario@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33015409','NUESTRA SEÑORA DEL ROSARIO','RIBADESELLA','ntrasradelrosarior@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33010333','NUEVA','LLANES','nueva@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33028544','NUEVAS TECNOLOGÍAS DE ESTÉTICA','GIJON','ntestetica@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33027825','NUEVAS TECNOLOGÍAS DE ESTÉTICA','OVIEDO','fpntestetica@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33028945','NUEVO GIJON','GIJON','eeingijon@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33029056','NUEVO ROCES','GIJON','eeinuevoroces@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33020880','NUMERO 1','GIJON','numero1@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33023236','NUMERO 5','AVILES','numero5@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33029093','OBANCA','CANGAS DEL NARCEA','obanca@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33023467','OCCIDENTE','TARAMUNDI','occident@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33028416','ORIENTE-COSTA','LLANES','orientecosta@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33028404','ORIENTE-INTERIOR','CANGAS DE ONIS','orienteinterior@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33016529','OSCOS','SANTA EULALIA DE OSCOS','oscos@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33021011','OVIEDO','OVIEDO','elfontan@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33700052','OVIEDO','OVIEDO','cproviedo@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33022293','OVIEDO','OVIEDO','eoiovied@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33015537','PABLO IGLESIAS','RIBERA DE ARRIBA','pabloigl@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33012421','PABLO MIAJA','OVIEDO','pmiaja@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33006159','PADRE FEIJOO','GIJON','padrefei@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33009380','PADRE GALO','VALDES','padregal@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33014995','PADRE NICOLAS ALBUERNE','PROAZA','padrenic@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33017111','PALACIO DE GRANDA','SIERO','colpalaciogranda@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33001137','PALACIO VALDES','AVILES','palaciov@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33022591','PANDO','OVIEDO','pando@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33013103','PARQUE INFANTIL','OVIEDO','parquein@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33028921','PARQUE NUEVO','LANGREO','eeilafelguera@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33005982','PATRONATO SAN JOSE','GIJON','patronatosanjose@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33001231','PAULA FRASSINETTI','AVILES','paulafrassinetti@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33011741','PEDRO PENZOL','NAVIA','pedropen@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33028258','PEGOYINOS','GIJON','pegoyinos@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33020776','PEÑA CARESES','SIERO','penacare@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33010229','PEÑA TU','LLANES','penatu@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33027837','PEÑAMAYOR','SIERO','penamayor@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33027527','PEÑAMAYOR','NAVA','nava@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33028970','PEQUENOS','SALAS','eeipequenos@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33013036','PEREZ DE AYALA','OVIEDO','perezaya@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33023571','PICOS DE EUROPA','ONIS','picosdee@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33029305','PILOÑA','PILOÑA','eeipilona@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33027850','PINÍN','NAVIA','eeinavia@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33027692','PINÍN','LANGREO','pinin@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33027977','PINTOR ALVARO DELGADO','VALDES','alvarode@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33005271','PINZALES','GIJON','pinzales@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33007814','PLACIDO BELTRAN','LANGREO','placidob@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33028064','POETA ÁNGEL GONZÁLEZ','OVIEDO','corredoria2@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33022244','POETA ANTON DE MARIRREGUERA','CARREÑO','poetaant@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33001149','POETA JUAN OCHOA','AVILES','poetajua@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33027345','POLA DE ALLANDE','ALLANDE','poladeallande@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33028805','POSADA','LLANES','eeiposada@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33023261','PRADO','CARAVIA','juanvigo@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33028969','PRAVIA','PRAVIA','eeipravia@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33023935','PRAVIA','PRAVIA','pravia@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33002166','PRIETO BANCES','CANDAMO','prietoba@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33028994','PRIMEROS PASOS','GIJON','ceiprimerospasos@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33001022','PRINCIPADO','AVILES','principado@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33017960','PRINCIPE DE ASTURIAS','TAPIA DE CASARIEGO','tapiadec@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33005362','PRINCIPE DE ASTURIAS','GIJON','principe@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33015161','PRINCIPE DE ASTURIAS','LAS REGUERAS','princisa@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33027394','PRINCIPE FELIPE','TINEO','navelgas@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33020326','RAMON ARECES','GRADO','ramonare@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33011647','RAMON DE CAMPOAMOR','NAVIA','ramoncam@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33024289','RAMON DE CAMPOAMOR','GIJON','ramondec@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33001381','RAMON MENENDEZ PIDAL','AVILES','rmpidal@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33009446','RAMON MUÑOZ','VALDES','ramonmun@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33028118','RAPACINOS','LANGREO','rapacinos@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33006123','REAL INSTITUTO JOVELLANOS','GIJON','iesjovel@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33003262','RECONQUISTA','CANGAS DE ONIS','reconqui@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33019798','RECONQUISTA','CANGAS DE ONIS','ehreconq@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33008223','REGINO MENENDEZ ANTUÑA','LANGREO','reginome@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33029329','REINA ADOSINDA','PRAVIA','reinaadosinda@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33028854','RENGOS','CANGAS DEL NARCEA','vegareng@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33016359','REY AURELIO','SAN MARTIN DEL REY AURELIO','reyaurel@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33023601','REY PELAYO','GIJON','reypelay@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33023650','REY PELAYO','CANGAS DE ONIS','iesreype@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33023111','RIA DEL EO','VEGADEO','riadeleo@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33028908','RIBADESELLA','RIBADESELLA','eeiribadesella@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33005064','RIEGO ARRIBA','CUDILLERO','riegoarr@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33023391','RIO CIBEA','CANGAS DEL NARCEA','riocibea@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33017315','RIO NORA','SIERO','rionora@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33021665','RIO PILES','GIJON','riopiles@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33013450','RIO SELLA','PARRES','riosella@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33023182','RIO TRUBIA','OVIEDO','riotrubi@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33010953','RIOTURBIO','MIERES DEL CAMINO','rioturbi@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33020041','ROCES','GIJON','iesroces@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33023017','ROSARIO ACUÑA','GIJON','rosarioa@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33028751','ROZONA FORMACION','AVILES','jollformacion@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33028891','RUBIN','OVIEDO','eeirubin@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33020132','SABUGO','AVILES','sabugo@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33610026','SAGRADA FAMILIA','CORVERA DE ASTURIAS','ceisagradafamilia@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33016131','SAGRADA FAMILIA','SAN MARTIN DEL REY AURELIO','sagradafamiliae@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33012573','SAGRADA FAMILIA','OVIEDO','sagradafamiliao@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33027862','SAGRADA FAMILIA-EL PILAR','LENA','sagradafamiliaelpilar@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33004141','SALINAS','CASTRILLON','salinas@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33016724','SALVADOR VEGA BERROS','SARIEGO','salvador@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33011477','SAN BARTOLOME','NAVA','sanbarto@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33028039','SAN CLAUDIO','OVIEDO','sanclaud@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33001459','SAN CRISTOBAL','AVILES','sancrist@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33009896','SAN CUCAO','LLANERA','sancucao@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33006287','SAN EUTIQUIO','GIJON','saneutiquio@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33024231','SAN EUTIQUIO','GIJON','ceisaneutiquio@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33003638','SAN FELIX','CARREÑO','sanfelix@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33001319','SAN FERNANDO','AVILES','sanfernando@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33012721','SAN IGNACIO','OVIEDO','sanignacio@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33007541','SAN JORGE','IBIAS','sanjorge@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33009975','SAN JOSE DE CALASANZ','LLANERA','sanjosed@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33023613','SAN LAZARO-ESCUELAS BLANCAS','OVIEDO','sanlazar@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33022335','SAN LORENZO','GIJON','sanlorenzo@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33023108','SAN MARTIN','SAN MARTIN DEL REY AURELIO','sanmarti@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33028121','SAN MARTÍN','SAN MARTIN DEL REY AURELIO','eeisanmartin@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33006007','SAN MIGUEL','GIJON','sanmiguel@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33009768','SAN MIGUEL','VALDES','sanmigue@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33001186','SAN NICOLAS DE BARI','AVILES','sannicolasdebari@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33000704','SAN PEDRO','ALLER','spedroel@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33012457','SAN PEDRO DE LOS ARCOS','OVIEDO','sanpedro@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33019439','SAN RAFAEL','VILLAVICIOSA','sanrafael@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33005933','SAN VICENTE DE PAUL','GIJON','sanvicentedepaul@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33006019','SANATORIO MARITIMO','GIJON','sanatoriomaritimo@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33010734','SANCHEZ LASTRA','MIERES DEL CAMINO','sanchezl@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33000522','SANTA BARBARA','ALLER','stabaroy@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33022165','SANTA BARBARA','SIERO','santabar@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33019804','SANTA BARBARA','LANGREO','stabarla@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33008831','SANTA CRISTINA DE LENA','LENA','stacristina@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33020156','SANTA EULALIA','MIERES DEL CAMINO','staeulal@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33014791','SANTA EULALIA DE MERIDA','PRAVIA','staeumer@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33012688','SANTA MARIA DEL NARANCO','OVIEDO','santamadelnaranco@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33022554','SANTA OLAYA','GIJON','santaola@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33012731','SANTA TERESA DE JESUS','OVIEDO','santateresadejesus@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33023388','SANTANA','CANGAS DEL NARCEA','santana@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33028520','SANTARBAS','CANGAS DEL NARCEA','santarba@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33010680','SANTIAGO APOSTOL','MIERES DEL CAMINO','santiago@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33001228','SANTO ANGEL DE LA GUARDA','AVILES','stoangeldelaguarda@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33006093','SANTO ANGEL DE LA GUARDA','GIJON','stoangeldelaguardag@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33012676','SANTO ANGEL DE LA GUARDA','OVIEDO','santoangeldelaguarda@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33024125','SANTO DOMINGO','NAVIA','santodomingo@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33012743','SANTO DOMINGO','OVIEDO','santodomingodeguzmano@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33010692','SANTO DOMINGO DE GUZMAN','MIERES DEL CAMINO','santodomingodeguzman@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33001344','SANTO TOMAS','AVILES','santotomas@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33011015','SANTULLANO','MIERES DEL CAMINO','santulla@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33028167','SECTORES INDUSTRIAL Y DE SERVICIOS','GIJON','industrialyservicios@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33023674','SELGAS','CUDILLERO','selgas@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33022566','SEVERO OCHOA','GIJON','severo@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33028040','SUROCCIDENTE','TINEO','ceatineo@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33029111','SVIDA','GIJON','svidagijon@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33027898','TAPIA-CASTROPOL','CASTROPOL','tapiacastropol@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33028763','TARAMUNDI','TARAMUNDI','eeitaramundi@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33010655','TEODORO CUESTA','MIERES DEL CAMINO','teodoroc@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33028933','TEVERGA','TEVERGA','eeiteverga@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33000376','THE ENGLISH SCHOOL OF ASTURIAS','LLANERA','eschoolast@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33027849','TINEO','TINEO','eeitineo@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33028911','TRAVESURES','LANGREO','eeitravesures@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33022360','TREMAÑES','GIJON','tremanes@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33028601','TREMAÑES','GIJON','eeitremanes@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33019725','TUDELA DE VEGUIN','OVIEDO','tudelave@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33007991','TURIELLOS','LANGREO','turiello@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33028155','UNIVERSIDAD LABORAL','GIJON','laboral@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33028830','VALDELLERA','LLANES','valdellera@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33027916','VALDEPARES','EL FRANCO','valdepar@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33023649','VALLE DE ALLER','ALLER','moreda@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33011064','VALLE DE TURON','MIERES DEL CAMINO','turon@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33023418','VALLE NAVIEGO','CANGAS DEL NARCEA','vallenav@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33011180','VEGA DE GUCEO','MIERES DEL CAMINO','vegaguce@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33028842','VEGA-LA CAMOCHA','GIJON','eeivega@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33022281','VENERANDA MANZANO','OVIEDO','venerand@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33021471','VENTANIELLES','OVIEDO','ventanie@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33017807','VENTURA PAZ SUAREZ','SOTO DEL BARCO','venturad@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33018642','VERDEAMOR','TINEO','verdeamo@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33022086','VERSALLES','AVILES','versalle@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33023923','VICTOR GARCIA DE LA CONCHA','VILLAVICIOSA','villavic@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33023480','VIELLA','SIERO','viella@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33028775','VIESQUES','GIJON','eeiviesques@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33020909','VILLAFRIA DE OTERO','OVIEDO','villafri@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33001150','VILLALEGRE','AVILES','villaleg@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33011209','VILLAPENDI','MIERES DEL CAMINO','villapen@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33028313','VILLARDEVEYO','LLANERA','villardeveyo@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33023595','VILLAYON','VILLAYON','villayon@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33016165','VIRGEN DE COVADONGA','SAN MARTIN DEL REY AURELIO','vcovadon@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33001401','VIRGEN DE LA LUZ','AVILES','vluz@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33001046','VIRGEN DE LAS MAREAS','AVILES','vmareas@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33015057','VIRGEN DEL ALBA','QUIROS','valba@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33006937','VIRGEN DEL FRESNO','GRADO','vfresno@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33005911','VIRGEN MEDIADORA','GIJON','virgenmediadora@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33005957','VIRGEN REINA','GIJON','virgenreina@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33008806','VITAL AZA','LENA','vitalaza@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33017182','XENTIQUINA','SIERO','solvay@educastur.org');
INSERT INTO centros (IDCENTRO, NOMBRE, MUNICIPIO, EMAIL) VALUES ('33006342','XOVE','GIJON','xove@educastur.org');



INSERT INTO actividad (tematica, duracion, resumen, pasos, curso, target, publica) VALUES
('Ciberseguridad básica', 45, 'Aprendizaje de normas de seguridad en internet', '1. Introducción\n2. Buenas prácticas\n3. Casos prácticos', '1ESO', 'Alumnado', true),
('Creación de contraseña segura', 30, 'Taller para generar contraseñas robustas', '1. ¿Qué es una contraseña segura?\n2. Generación práctica\n3. Evaluación de ejemplos', '2ESO', 'Alumnado', true),
('Uso ético de la tecnología', 60, 'Reflexión sobre el uso responsable de los dispositivos', '1. Debate inicial\n2. Casos éticos\n3. Conclusiones', '3ESO', 'Alumnado', false),
('Netiqueta en redes sociales', 45, 'Buenas prácticas comunicativas online', '1. Qué es netiqueta\n2. Simulaciones\n3. Roleplay', '4ESO', 'Alumnado', true),
('Gestión del tiempo con apps', 50, 'Uso de herramientas digitales para la organización personal', '1. Introducción a apps\n2. Configuración\n3. Simulación de uso diario', '1BH', 'Alumnado', true),
('Taller de fake news', 60, 'Cómo identificar noticias falsas en Internet', '1. Teoría\n2. Análisis de ejemplos\n3. Creación de una noticia falsa', '2BH', 'Alumnado', true),
('Autoconocimiento digital', 45, 'Concienciación sobre identidad digital', '1. ¿Qué es la huella digital?\n2. Ejercicio de búsqueda personal\n3. Debate', '1ESO', 'Alumnado', false),
('Privacidad en móviles', 40, 'Configuración de privacidad en dispositivos móviles', '1. Ajustes básicos\n2. Casos comunes\n3. Revisión de permisos', 'FPBASICA', 'Alumnado', true),
('Ciberbullying: prevención y actuación', 60, 'Identificación y gestión del ciberacoso', '1. Teoría\n2. Roleplays\n3. Plan de actuación', '2ESO', 'Alumnado', true),
('Diseño de cartel digital', 50, 'Uso de herramientas online para cartelería', '1. Canva o similar\n2. Diseño guiado\n3. Presentación', 'ESO', 'Alumnado', false),
('Taller de IA en la vida diaria', 60, 'Reflexión sobre el impacto de la inteligencia artificial', '1. ¿Qué es la IA?\n2. Casos reales\n3. Discusión en grupo', '4ESO', 'Alumnado', true),
('Aplicaciones educativas', 45, 'Exploración de apps útiles para estudiar', '1. Búsqueda\n2. Comparativa\n3. Uso guiado', '3ESO', 'Alumnado', true),
('Desinformación en internet', 50, 'Cómo contrastar fuentes online', '1. Detectar bulos\n2. Herramientas de verificación\n3. Creación de ejemplo', '1BH', 'Alumnado', true),
('Herramientas de colaboración online', 55, 'Uso básico de Google Drive y similares', '1. Crear y compartir documentos\n2. Edición colaborativa\n3. Feedback', '2BH', 'Alumnado', false),
('Protección de datos personales', 45, 'Concienciación sobre el tratamiento de datos', '1. Legislación básica\n2. Análisis de redes\n3. Recomendaciones', '1ESO', 'Alumnado', true),
('Taller de edición de vídeo', 60, 'Introducción a herramientas de edición gratuitas', '1. Cargar material\n2. Edición básica\n3. Exportación', 'CICLOS GRADO MEDIO', 'Alumnado', true),
('Aplicaciones de calendario', 30, 'Organización con Google Calendar', '1. Crear eventos\n2. Recordatorios\n3. Integración con Gmail', 'CICLOS GRADO SUPERIOR', 'Alumnado', false),
('Digital detox', 50, 'Técnicas para reducir el uso de pantallas', '1. Debate\n2. Técnicas de desconexión\n3. Compromisos', '2ESO', 'Alumnado', true),
('Prevención del phishing', 45, 'Reconocimiento y prevención del fraude online', '1. Tipos de phishing\n2. Ejemplos\n3. Simulacro', '3ESO', 'Alumnado', true),
('Gestión emocional en redes', 55, 'Impacto emocional de las redes sociales', '1. Casos reales\n2. Discusión\n3. Técnicas de cuidado', '4ESO', 'Alumnado', false),
('Organización de tareas con Trello', 40, 'Uso de tableros para gestión personal', '1. Crear tablero\n2. Tareas y columnas\n3. Seguimiento', 'FPBASICA', 'Alumnado', true),
('Creación de podcast educativo', 60, 'Guionizar y grabar un podcast', '1. Idea\n2. Grabación\n3. Edición', 'CICLOS GRADO MEDIO', 'Alumnado', true),
('Creación de CV digital', 45, 'Uso de plantillas para CV moderno', '1. Selección de plantilla\n2. Rellenado\n3. Exportación', 'CICLOS GRADO SUPERIOR', 'Alumnado', true),
('Comparativa de buscadores', 30, 'Análisis de Google vs. alternativas', '1. Ecosia, DuckDuckGo\n2. Resultados\n3. Privacidad', '1BH', 'Alumnado', false),
('Taller de presentaciones efectivas', 50, 'Diseño y exposición', '1. Buenas prácticas\n2. Ejemplos\n3. Exposición breve', '2BH', 'Alumnado', true),
('Planificación semanal', 40, 'Creación de rutinas personales', '1. Plantillas\n2. Priorización\n3. Ajustes', '1ESO', 'Alumnado', true),
('Uso de Drive para trabajos colaborativos', 55, 'Creación de carpetas y edición conjunta', '1. Crear documento compartido\n2. Roles\n3. Revisión', '2ESO', 'Alumnado', true),
('Simulación de entrevista laboral', 60, 'Preparación y simulacro', '1. Roles\n2. Entrevistas\n3. Evaluación', 'CICLOS GRADO MEDIO', 'Alumnado', true),
('Taller de Canva para infografías', 45, 'Diseño visual de conceptos', '1. Elección de tema\n2. Diseño\n3. Presentación', '3ESO', 'Alumnado', true),
('Edición básica de imagen', 60, 'GIMP u otras herramientas gratuitas', '1. Herramientas básicas\n2. Ejercicio práctico\n3. Guardado', '4ESO', 'Alumnado', false),
('Identidad digital profesional', 50, 'Creación de perfil profesional', '1. ¿Qué es LinkedIn?\n2. Perfiles ejemplo\n3. Primeros pasos', 'CICLOS GRADO SUPERIOR', 'Alumnado', true),
('Seguridad en redes públicas', 40, 'Prevención de riesgos en wifi abierta', '1. Casos reales\n2. Buenas prácticas\n3. Recomendaciones', 'ESO', 'Alumnado', true),
('Creación de formularios', 45, 'Google Forms y aplicaciones', '1. Tipos de preguntas\n2. Diseño y distribución\n3. Resultados', '2BH', 'Alumnado', true),
('Simulación de empresa digital', 60, 'Emprendimiento en entornos online', '1. Roles y tareas\n2. Marketing\n3. Evaluación', 'FORMACION PROFESIONAL', 'Alumnado', true),
('Responsabilidad digital', 50, 'Reflexión sobre derechos y deberes digitales', '1. Conceptos básicos\n2. Casos éticos\n3. Debate', 'ESO', 'Alumnado', false),
('Búsqueda efectiva en internet', 30, 'Técnicas para buscar información fiable', '1. Comandos de búsqueda\n2. Comparación de fuentes\n3. Ejercicio práctico', '1ESO', 'Alumnado', true),
('Taller de Scratch básico', 60, 'Introducción a la programación con bloques', '1. Presentación de Scratch\n2. Proyecto simple\n3. Compartir', '1ESO', 'Alumnado', true),
('Creación de blog escolar', 55, 'Introducción a Blogger o Wordpress', '1. Crear cuenta\n2. Primera entrada\n3. Personalización', '3ESO', 'Alumnado', true),
('Taller de Kahoot', 30, 'Diseñar un test interactivo', '1. Crear cuenta\n2. Crear preguntas\n3. Jugar en grupo', '2ESO', 'Alumnado', true),
('Gamificación en el aula', 50, 'Aplicaciones para dinamizar', '1. ClassDojo, Quizizz\n2. Simulación\n3. Evaluación', 'ESO', 'Alumnado', false),
('Mi primer CV online', 45, 'Taller orientado al empleo', '1. Plantilla Canva\n2. Edición guiada\n3. Feedback', 'FPBASICA', 'Alumnado', true),
('Creación de logotipo', 50, 'Diseño gráfico inicial', '1. Boceto manual\n2. Digitalización\n3. Evaluación', 'CICLOS GRADO MEDIO', 'Alumnado', true),
('Uso de Padlet para lluvia de ideas', 40, 'Herramienta colaborativa', '1. Crear muro\n2. Publicación anónima\n3. Debate', '2BH', 'Alumnado', true),
('Hackeo ético básico', 60, 'Introducción a pruebas de vulnerabilidad', '1. Conceptos\n2. Simulación guiada\n3. Conclusiones', 'CICLOS GRADO SUPERIOR', 'Alumnado', false),
('Desarrollo de app con MIT App Inventor', 60, 'Primera app sencilla', '1. Crear cuenta\n2. Elegir plantilla\n3. Probar', 'FORMACION PROFESIONAL', 'Alumnado', true),
('Storytelling digital', 45, 'Narración usando herramientas TIC', '1. Estructura narrativa\n2. Diseño en Canva\n3. Presentación', '4ESO', 'Alumnado', true),
('Taller de OBS Studio', 60, 'Grabación de pantalla profesional', '1. Configuración\n2. Prueba de grabación\n3. Exportación', 'CICLOS GRADO SUPERIOR', 'Alumnado', true),
('Taller de edición de audio', 50, 'Audacity básico', '1. Importar audio\n2. Cortes y efectos\n3. Exportar', 'CICLOS GRADO MEDIO', 'Alumnado', true);
*/